#!/bin/bash

# Input params
# $1 BLUE_ASN 
# $2 BLUE_OUTSIDE_IP1 
# $3 BLUE_OUTSIDE_IP2 
# $4 BLUE_INSIDE_IP1 
# $5 BLUE_INSIDE_IP2  
# $6 GREEN_ASN 
# $7 GREEN_OUTSIDE_IP1 
# $8 GREEN_INSIDE_IP1 
# $9 GREEN_INSIDE_IP2 
# $10 TUNNEL1_PRESHARED_KEY 
# $11 TUNNEL2_PRESHARED_KEY 
# $12 GREEN_NETWORKS 
# $13 GIT_REPO 
